#!/bin/sh /etc/rc.common

# Copyright 2026 肖其顿 (XIAO QI DUN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

START=99
USE_PROCD=1

start_service() {
	/usr/sbin/nftrl apply
}

stop_service() {
	/usr/sbin/nftrl clean
}

reload_service() {
	/usr/sbin/nftrl apply
}

service_triggers() {
	procd_add_reload_trigger "nftrl"
}